import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ThemeProvider } from '~/components/theme/theme-provider';

import './globals.css';
import 'react-grid-layout/css/styles.css'; // Import CSS for layout styles
import 'react-resizable/css/styles.css'; // Import CSS for resize handles
import FlickeringGrid from '~/components/ui/flickering-grid';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <section>
            <FlickeringGrid
              className="z-0 absolute inset-0 right-0 bottom-0 size-full"
              squareSize={4}
              gridGap={8}
              color="#6B7280"
              maxOpacity={0.5}
              flickerChance={0.1}
            />
            {children}
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
